name = "dont-step"
compatibility_date = "2025-06-07"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "dont-step"
database_id = "2b8cb573-2a64-4e83-86ec-8771da35396d"
